
import { StateGraph, Annotation, START, END } from "@langchain/langgraph";
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { ChatGroq } from "@langchain/groq";
import { ChatOpenAI } from "@langchain/openai";
import { BaseMessage, HumanMessage, SystemMessage } from "@langchain/core/messages";
import { retrieveMemory, storeMemory } from "./memory";

console.log("[Graph] Environment Check:", {
  hasGroq: !!process.env.GROQ_API_KEY,
  hasGemini: !!process.env.GOOGLE_GENERATIVE_AI_API_KEY,
  hasOpenRouter: !!process.env.OPENROUTER_API_KEY,
  hasTavily: !!process.env.TAVILY_API_KEY,
});

let geminiFlash: ChatGoogleGenerativeAI | null = null;
let groqLlama: ChatGroq | null = null;
let openRouterMiniMax: ChatOpenAI | null = null;
let openRouterGLM: ChatOpenAI | null = null;

function getOpenRouterMiniMax() {
  if (!openRouterMiniMax && process.env.OPENROUTER_API_KEY) {
    openRouterMiniMax = new ChatOpenAI({
      modelName: "minimax/minimax-m2.5:free",
      apiKey: process.env.OPENROUTER_API_KEY,
      configuration: { baseURL: "https://openrouter.ai/api/v1" },
      maxTokens: 2048,
    });
  }
  return openRouterMiniMax;
}

function getOpenRouterGLM() {
  if (!openRouterGLM && process.env.OPENROUTER_API_KEY) {
    openRouterGLM = new ChatOpenAI({
      modelName: "z-ai/glm-4.5-air:free",
      apiKey: process.env.OPENROUTER_API_KEY,
      configuration: { baseURL: "https://openrouter.ai/api/v1" },
      maxTokens: 2048,
    });
  }
  return openRouterGLM;
}

// OpenCode.ai is a CLI tool, not an API provider — removed

function getGemini() {
  if (!geminiFlash && process.env.GOOGLE_GENERATIVE_AI_API_KEY) {
    geminiFlash = new ChatGoogleGenerativeAI({
      model: "gemini-1.5-flash",
      apiKey: process.env.GOOGLE_GENERATIVE_AI_API_KEY,
      maxOutputTokens: 2048,
    });
  }
  return geminiFlash;
}

function getGroq() {
  if (!groqLlama && process.env.GROQ_API_KEY) {
    groqLlama = new ChatGroq({
      model: "llama-3.3-70b-versatile",
      apiKey: process.env.GROQ_API_KEY,
      maxTokens: 2048,
    });
  }
  return groqLlama;
}

import { Octokit } from "@octokit/rest";

let GITHUB_OWNER = process.env.GITHUB_OWNER || "k0-123";
let GITHUB_REPO = process.env.GITHUB_REPO || "agent-flow";

async function githubAction(action: "list" | "read" | "commit" | "pr", params: any): Promise<string> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) return "GitHub token missing. Please add GITHUB_TOKEN to .env";

  const octokit = new Octokit({ auth: token });
  const owner = GITHUB_OWNER;
  const repo = GITHUB_REPO;

  try {
    if (action === "list") {
      const { data } = await octokit.repos.getContent({ owner, repo, path: params.path || "" });
      if (Array.isArray(data)) {
        return data.map(f => `${f.type === "dir" ? "[DIR]" : "[FILE]"} ${f.path}`).join("\n");
      }
      return "Path is not a directory.";
    }

    if (action === "read") {
      const { data }: any = await octokit.repos.getContent({ owner, repo, path: params.path });
      return Buffer.from(data.content, "base64").toString();
    }

    if (action === "commit") {
      // Step 1: Get current ref
      const { data: ref } = await octokit.git.getRef({ owner, repo, ref: "heads/main" });
      const baseSha = ref.object.sha;

      // Step 2: Create new branch
      const branchName = `agent-update-${Date.now()}`;
      await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branchName}`, sha: baseSha });

      // Step 3: Create commit
      await octokit.repos.createOrUpdateFileContents({
        owner, repo,
        path: params.path,
        message: params.message || "Automated update from Agent Orchestrator",
        content: Buffer.from(params.content).toString("base64"),
        branch: branchName,
      });

      // Step 4: Create PR
      const { data: pr } = await octokit.pulls.create({
        owner, repo,
        title: params.prTitle || "Agent Suggestion: " + params.path,
        head: branchName,
        base: "main",
        body: params.prBody || "This PR was automatically generated by the Senior Builder agent.",
      });

      return `Successfully created PR: ${pr.html_url}`;
    }

    return "Unknown GitHub action.";
  } catch (err) {
    return `GitHub Error: ${err instanceof Error ? err.message : String(err)}`;
  }
}

async function tavilySearch(query: string): Promise<string> {
  const apiKey = process.env.TAVILY_API_KEY;
  if (!apiKey) return "Web search unavailable (API key missing).";
  try {
    const res = await fetch("https://api.tavily.com/search", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ api_key: apiKey, query, search_depth: "basic" }),
    });
    const data = await res.json();
    return data.results?.map((r: any) => `[${r.title}] ${r.content}`).join("\n\n") ?? "No results found.";
  } catch (err) {
    return `Search error: ${err instanceof Error ? err.message : String(err)}`;
  }
}

interface Issue {
  id: string; title: string;
  status: 'todo' | 'in_progress' | 'completed' | 'blocked';
  assignee: string;
  priority: 'low' | 'medium' | 'high';
}

interface AgentUpdate {
  agentId: string;
  newStatus: "idle" | "working" | "moving" | "learning" | "reviewing";
  actionLog: string;
}

interface Budget { limit: number; spent: number; }

interface RoadmapStep {
  agentId: string;
  task: string;
  status: "pending" | "completed" | "rejected";
  tools?: string[];
}

const AgentState = Annotation.Root({
  task: Annotation<string>(),
  messages: Annotation<BaseMessage[]>({ reducer: (a, b) => [...a, ...b], default: () => [] }),
  auditLog: Annotation<string[]>({ reducer: (a, b) => [...a, ...b], default: () => [] }),
  activeIssues: Annotation<Issue[]>({ reducer: (_, b) => b, default: () => [] }),
  agentUpdates: Annotation<AgentUpdate[]>({ reducer: (a, b) => [...a, ...b], default: () => [] }),
  budget: Annotation<Budget>({ reducer: (_, b) => b, default: () => ({ limit: 10.0, spent: 0.0 }) }),
  roadmap: Annotation<RoadmapStep[]>({ reducer: (_, b) => b, default: () => [] }),
  currentStepIndex: Annotation<number>({ reducer: (_, b) => b, default: () => 0 }),
  workerOutput: Annotation<string>({ reducer: (_, b) => b, default: () => "" }),
  reviewFeedback: Annotation<string | null>({ reducer: (_, b) => b, default: () => null }),
  result: Annotation<string>({ reducer: (_, b) => b, default: () => "" }),
  retryCount: Annotation<number>({ reducer: (_, b) => b, default: () => 0 }),
  error: Annotation<string | null>({ reducer: (_, b) => b, default: () => null }),
});

type AgentStateType = typeof AgentState.State;

async function resilientInvoke(
  messages: BaseMessage[],
  state: AgentStateType,
  preferredModel?: "minimax" | "glm"
): Promise<{ content: string; tokenCost: number }> {
  if (state.budget.spent >= state.budget.limit) throw new Error("Budget exhausted.");
  
  const attempts = [];
  if (preferredModel === "glm") {
    attempts.push({ name: "OpenRouter GLM", fn: getOpenRouterGLM });
    attempts.push({ name: "OpenRouter MiniMax", fn: getOpenRouterMiniMax });
  } else {
    attempts.push({ name: "OpenRouter MiniMax", fn: getOpenRouterMiniMax });
    attempts.push({ name: "OpenRouter GLM", fn: getOpenRouterGLM });
  }
  
  attempts.push({ name: "Groq", fn: getGroq });
  attempts.push({ name: "Gemini", fn: getGemini });

  for (const { name, fn } of attempts) {
    const model = fn();
    if (!model) continue;
    try {
      console.log(`[Graph] Invoking ${name}...`);
      // Add a timeout to the invoke call
      const response = await Promise.race([
        model.invoke(messages),
        new Promise((_, reject) => setTimeout(() => reject(new Error(`${name} timeout after 90s`)), 90000))
      ]) as any;
      
      const content = typeof response.content === "string" ? response.content : JSON.stringify(response.content);
      const tokenCost = (content.length / 4) * 0.000000075;
      console.log(`[Graph] ${name} success.`);
      return { content, tokenCost };
    } catch (err) {
      console.warn(`[Invoke] ${name} failed: ${err}`);
    }
  }
  throw new Error("All LLM attempts failed.");
}

function audit(agentId: string, msg: string): string {
  const ts = new Date().toLocaleTimeString("en-US", { hour12: false });
  return `[${ts}] [${agentId.toUpperCase()}] ${msg}`;
}

// Strips model-specific artifacts (MiniMax tool_call XML, JSON blobs, etc.) from LLM output
function sanitizeResponse(raw: string): string {
  let cleaned = raw;
  // Remove MiniMax tool_call XML blocks
  cleaned = cleaned.replace(/<minimax:tool_call>[\s\S]*?<\/minimax:tool_call>/g, "").trim();
  // Remove any generic XML tool invocations
  cleaned = cleaned.replace(/<invoke[\s\S]*?<\/invoke>/g, "").trim();
  // Remove JSON blobs that look like tool parameters ({"QUERY":..., "MAX_RESULTS":...})
  cleaned = cleaned.replace(/^\s*\{["'](?:QUERY|query|MAX_RESULTS|max_results)["'][\s\S]*?\}\s*/gm, "").trim();
  // Remove lines that are only whitespace after cleanup
  cleaned = cleaned.split("\n").filter(l => l.trim().length > 0).join("\n");
  return cleaned || raw; // fallback to raw if everything got stripped
}

async function ceoNode(state: AgentStateType): Promise<Partial<AgentStateType>> {
  // Power up: CEO can go online for research tasks
  let webResearch = "";
  const taskLower = state.task.toLowerCase();
  if (taskLower.includes("research") || taskLower.includes("who is") || taskLower.includes("what is") || taskLower.includes("find")) {
    webResearch = await tavilySearch(state.task);
  }

  const systemPrompt = `You are Karan, CEO of a multi-agent team. Your ONLY job is to create a roadmap.

TASK: ${state.task}

IMPORTANT RULES:
- You MUST respond ONLY with the ROADMAP format below. Nothing else.
- Do NOT write code. Do NOT answer the question yourself. Do NOT use tool calls.
- Do NOT output XML, JSON, or any markup.
- For SIMPLE questions (who/what/when/where/why, factual lookups), create ONLY 1 step assigned to "senior".
- For COMPLEX tasks (build something, create code, design a system), use 2-4 steps with appropriate agents.
- NEVER assign more than 4 steps total.

Available Agents:
- senior: Lead Developer. Best for: answering questions, code, architecture, GitHub operations.
- intern: Support Dev. Best for: documentation, simple fixes, formatting.
- offer: Offer Architect. Best for: business strategy, pricing, market analysis.
- growth: Growth Hacker. Best for: marketing, traffic, viral strategies.
- funnel: Funnel Engineer. Best for: landing pages, email sequences, customer journeys.
- designer: Visual Designer. Best for: UI/UX, visual assets, brand work.

${webResearch ? `RESEARCH CONTEXT (use this to inform your roadmap):\n${webResearch}\n` : ""}

Respond with EXACTLY this format and NOTHING else:
ROADMAP:
1. [agentId]: [clear task description]
TOOLS: [none or comma-separated: search, github:list, github:read, github:commit]`;

  const { content, tokenCost } = await resilientInvoke([
    new SystemMessage(systemPrompt),
    new HumanMessage(state.task),
  ], state, "glm");

  const sanitized = sanitizeResponse(content);
  console.log("[CEO] Raw response:", content.slice(0, 200));
  console.log("[CEO] Sanitized:", sanitized.slice(0, 200));

  const roadmapLines = sanitized.split("\n").filter(l => l.includes(":") && l.match(/^\d/));
  let roadmap: RoadmapStep[] = roadmapLines
    .map(line => {
      const parts = line.split(":");
      const idPart = parts[0].replace(/^\d+\.\s*/, "").toLowerCase().trim();
      const taskPart = parts.slice(1).join(":").trim();
      const validId = ["ceo", "senior", "intern", "offer", "growth", "funnel", "designer"].includes(idPart) ? idPart : "senior";
      return { agentId: validId, task: taskPart, status: "pending" as const } as RoadmapStep;
    })
    .filter((s): s is RoadmapStep => !!s && s.task.length > 2);

  // Fallback: if CEO produced no valid roadmap, create a single-step one
  if (roadmap.length === 0) {
    roadmap = [{ agentId: "senior", task: state.task, status: "pending" }];
  }

  // Cap at 4 steps max to prevent runaway orchestration
  roadmap = roadmap.slice(0, 4);

  const tools = sanitized.match(/TOOLS:\s*(.+)/i)?.[1]?.split(",").map(t => t.trim()) ?? [];

  return {
    roadmap,
    currentStepIndex: 0,
    budget: { ...state.budget, spent: state.budget.spent + tokenCost },
    auditLog: [audit("ceo", `Roadmap created: ${roadmap.length} steps. Tools: ${tools.join(", ")}`)],
    agentUpdates: [{ agentId: "ceo", newStatus: "working", actionLog: "Mission Roadmap Designed." }],
  };
}

async function workerNode(state: AgentStateType): Promise<Partial<AgentStateType>> {
  const step = state.roadmap[state.currentStepIndex];
  if (!step) return { error: "No step found" };

  // Check for GitHub tools in step
  let githubContext = "";
  if (step.agentId === "senior") {
    if (step.task.toLowerCase().includes("list files")) {
      githubContext = await githubAction("list", {});
    } else if (step.task.toLowerCase().includes("read file")) {
      const path = step.task.match(/read file ([\w./-]+)/)?.[1];
      if (path) githubContext = await githubAction("read", { path });
    }
  }

  // Check for search tools
  let searchContext = "";
  if (step.task.toLowerCase().includes("search") || step.task.toLowerCase().includes("research") ||
      step.task.toLowerCase().includes("who is") || step.task.toLowerCase().includes("what is") ||
      step.task.toLowerCase().includes("find") || step.task.toLowerCase().includes("current")) {
    searchContext = await tavilySearch(step.task);
  }

  const systemPrompt = `You are ${step.agentId}, a specialist on a professional team.

YOUR TASK: ${step.task}

CRITICAL RULES — VIOLATION MEANS FAILURE:
1. Respond ONLY in plain text. No XML, no JSON, no HTML, no markup of any kind.
2. Do NOT output <tool_call>, <invoke>, <minimax:tool_call>, or ANY XML tags. These are FORBIDDEN.
3. Do NOT hallucinate tools or APIs. You have NO tools. Just answer directly.
4. Stay STRICTLY on topic. Answer ONLY what is asked.
5. Be concise but complete. Give the actual answer, not meta-commentary.

${state.reviewFeedback ? `REVISION NOTES FROM CEO: ${state.reviewFeedback}` : ""}
${githubContext ? `GITHUB DATA:\n${githubContext}` : ""}
${searchContext ? `SEARCH RESULTS:\n${searchContext}` : ""}

Respond with EXACTLY this format:
ACTION: [one sentence describing what you did]
RESULT: [your complete, direct answer to the task]`;

  const { content, tokenCost } = await resilientInvoke([
    new SystemMessage(systemPrompt),
    new HumanMessage(`Complete this task now: ${step.task}`),
  ], state, "minimax");

  // Sanitize the response to remove any model artifacts
  const sanitized = sanitizeResponse(content);
  console.log("[Worker] Raw:", content.slice(0, 200));
  console.log("[Worker] Sanitized:", sanitized.slice(0, 200));

  if (sanitized.includes("GITHUB_ACTION: commit")) {
    const path = sanitized.match(/PATH:\s*(.+)/)?.[1]?.trim();
    const message = sanitized.match(/MESSAGE:\s*(.+)/)?.[1]?.trim();
    const fileContent = sanitized.match(/CONTENT:\s*([\s\S]+)/)?.[1]?.trim();

    if (path && fileContent) {
      const result = await githubAction("commit", { path, message, content: fileContent });
      return {
        workerOutput: result,
        budget: { ...state.budget, spent: state.budget.spent + tokenCost },
        auditLog: [audit(step.agentId, "Committed changes to GitHub: " + path)],
        agentUpdates: [{ agentId: step.agentId, newStatus: "working", actionLog: "GitHub Commit Executed." }],
      };
    }
  }

  const action = sanitized.match(/ACTION:\s*([\s\S]+?)(?=RESULT:|$)/i)?.[1]?.trim() ?? "Task complete.";
  let result = sanitized.match(/RESULT:\s*([\s\S]+)$/i)?.[1]?.trim() ?? sanitized;

  // Final safety net: if result still contains tool call artifacts, strip them
  result = sanitizeResponse(result);

  return {
    workerOutput: result,
    budget: { ...state.budget, spent: state.budget.spent + tokenCost },
    auditLog: [audit(step.agentId, action)],
    agentUpdates: [{ agentId: step.agentId, newStatus: "working", actionLog: action }],
    result: result,
    messages: [new HumanMessage(`${step.agentId}: ${action}`)],
  };
}

async function reviewNode(state: AgentStateType): Promise<Partial<AgentStateType>> {
  const step = state.roadmap[state.currentStepIndex];

  // Quick-reject: if worker output is mostly XML/tool calls, auto-reject
  const xmlRatio = (state.workerOutput.match(/<[^>]+>/g) || []).length;
  if (xmlRatio > 3) {
    console.warn("[Review] Auto-rejecting: output contains too many XML tags.");
    const newRoadmap = [...state.roadmap];
    newRoadmap[state.currentStepIndex].status = "rejected";
    return {
      roadmap: newRoadmap,
      reviewFeedback: "Your response contained XML/tool_call tags. Respond in PLAIN TEXT only. No XML, no JSON, no tool calls.",
      currentStepIndex: state.currentStepIndex,
      retryCount: state.retryCount + 1,
      auditLog: [audit("ceo", `Review for ${step.agentId}: ❌ AUTO-REJECTED (XML artifacts detected)`)],
      agentUpdates: [{ agentId: "ceo", newStatus: "reviewing", actionLog: "Auto-rejected: XML in output." }],
      result: state.result,
      budget: state.budget,
    };
  }

  const systemPrompt = `You are Karan, CEO. Review this work.

ORIGINAL TASK: ${step.task}
WORKER OUTPUT: ${state.workerOutput}

RULES:
- Respond ONLY in plain text. No XML, no JSON.
- If the output actually answers the task, APPROVE it.
- If the output is off-topic, contains code when none was asked for, or has XML/tool_call artifacts, REJECT it.
- Be lenient — if the answer is roughly correct, APPROVE.

Respond with EXACTLY:
STATUS: APPROVED
FEEDBACK: [brief reason]

OR:
STATUS: REJECTED
FEEDBACK: [what needs fixing]`;

  const { content, tokenCost } = await resilientInvoke([
    new SystemMessage(systemPrompt),
    new HumanMessage(`Review work from ${step.agentId}`),
  ], state, "glm");

  const sanitized = sanitizeResponse(content);
  const isApproved = sanitized.includes("APPROVED");
  const feedback = sanitized.match(/FEEDBACK:\s*([\s\S]+?)$/i)?.[1]?.trim() ?? "Review complete.";

  const newRoadmap = [...state.roadmap];
  if (isApproved) {
    newRoadmap[state.currentStepIndex].status = "completed";
  } else {
    newRoadmap[state.currentStepIndex].status = "rejected";
  }

  return {
    roadmap: newRoadmap,
    reviewFeedback: isApproved ? null : feedback,
    currentStepIndex: isApproved ? state.currentStepIndex + 1 : state.currentStepIndex,
    retryCount: isApproved ? 0 : state.retryCount + 1,
    auditLog: [audit("ceo", `Review for ${step.agentId}: ${isApproved ? "✅ APPROVED" : "❌ REJECTED"}`)],
    agentUpdates: [{ agentId: "ceo", newStatus: "reviewing", actionLog: isApproved ? "Work validated." : `Revision requested: ${feedback.slice(0, 50)}...` }],
    result: isApproved ? state.workerOutput : state.result,
    budget: { ...state.budget, spent: state.budget.spent + tokenCost },
  };
}


function routeAfterReview(state: AgentStateType) {
  // If rejected, allow up to 2 retries then force-advance
  if (state.reviewFeedback) {
    if (state.retryCount >= 2) {
      console.warn("[Route] Max retries reached, force-advancing.");
      return state.currentStepIndex >= state.roadmap.length ? "end" : "worker";
    }
    return "worker";
  }
  if (state.currentStepIndex >= state.roadmap.length) return "end";
  return "worker";
}

const workflow = new StateGraph(AgentState)
  .addNode("ceo", ceoNode)
  .addNode("worker", workerNode)
  .addNode("review", reviewNode)
  .addEdge(START, "ceo")
  .addEdge("ceo", "worker")
  .addEdge("worker", "review")
  .addConditionalEdges("review", routeAfterReview, {
    worker: "worker",
    end: END,
  });

export const agentGraph = workflow.compile();

export async function* runAgentStream(task: string, goal?: string, env?: any) {
  // Update configuration from env if provided
  if (env) {
    if (env.GITHUB_OWNER) GITHUB_OWNER = env.GITHUB_OWNER;
    if (env.GITHUB_REPO) GITHUB_REPO = env.GITHUB_REPO;
    // We can also override API keys here if needed
  }

  const initial = {
    task: goal ? `Goal: ${goal}\n\nTask: ${task}` : task,
    messages: [],
    auditLog: [`[SYSTEM] Multi-Step Orchestrator active. Goal: ${goal || 'Complete task'}.`],
    agentUpdates: [],
    budget: { limit: 10.0, spent: 0.0 },
    roadmap: [],
    currentStepIndex: 0,
    workerOutput: "",
    reviewFeedback: null,
    result: "",
    retryCount: 0,
    error: null,
  };

  try {
    let latestResult = "";
    const stream = await agentGraph.stream(initial, { streamMode: "updates" });
    for await (const chunk of stream) {
      if (!chunk) continue;
      const [nodeName, nodeState] = Object.entries(chunk)[0] as [string, Partial<AgentStateType>];
      
      let newResultVal = nodeState.result || nodeState.workerOutput;
      let resultToSend = "";
      
      if (newResultVal && newResultVal !== latestResult) {
        latestResult = newResultVal;
        resultToSend = latestResult; // Only send when it changes to prevent duplicate deliverables
      }
      
      console.log(`[Graph] Node finished: ${nodeName}`, { result: latestResult.slice(0, 80) });

      const currentAgentId = nodeState.agentUpdates?.[0]?.agentId 
        || nodeState.roadmap?.[nodeState.currentStepIndex || 0]?.agentId 
        || "worker";

      // Yield ALL nodes so the SSE stream gets updates
      yield {
        agentId: nodeName === "review" || nodeName === "ceo" ? "ceo" : currentAgentId,
        targetAgentId: nodeName === "worker" ? "ceo" : (nodeName === "review" ? currentAgentId : null),
        actionLog: nodeState.agentUpdates?.[0]?.actionLog ?? "Processing...",
        newStatus: nodeState.agentUpdates?.[0]?.newStatus ?? "working",
        auditLog: nodeState.auditLog ?? [],
        budget: nodeState.budget,
        roadmap: nodeState.roadmap,
        result: resultToSend,
      };
    }
    yield { status: "completed", agentId: "system", actionLog: "Mission successful.", auditLog: ["[SYSTEM] Roadmap fully executed and validated."], result: "" };
  } catch (err) {
    console.error("[Graph] Stream error:", err);
    yield { status: "error", agentId: "system", actionLog: `Fatal: ${err}`, auditLog: [`[ERROR] ${err}`], result: "" };
  }
}
