// Auto-generated by scripts/gen_ds_index.js
import ds_agentic from './agentic/DESIGN.md';
import ds_airbnb from './airbnb/DESIGN.md';
import ds_airtable from './airtable/DESIGN.md';
import ds_ant from './ant/DESIGN.md';
import ds_apple from './apple/DESIGN.md';
import ds_application from './application/DESIGN.md';
import ds_arc from './arc/DESIGN.md';
import ds_artistic from './artistic/DESIGN.md';
import ds_atelier_zero from './atelier-zero/DESIGN.md';
import ds_bento from './bento/DESIGN.md';
import ds_binance from './binance/DESIGN.md';
import ds_bmw from './bmw/DESIGN.md';
import ds_bmw_m from './bmw-m/DESIGN.md';
import ds_bold from './bold/DESIGN.md';
import ds_brutalism from './brutalism/DESIGN.md';
import ds_bugatti from './bugatti/DESIGN.md';
import ds_cafe from './cafe/DESIGN.md';
import ds_cal from './cal/DESIGN.md';
import ds_canva from './canva/DESIGN.md';
import ds_cisco from './cisco/DESIGN.md';
import ds_claude from './claude/DESIGN.md';
import ds_clay from './clay/DESIGN.md';
import ds_claymorphism from './claymorphism/DESIGN.md';
import ds_clean from './clean/DESIGN.md';
import ds_clickhouse from './clickhouse/DESIGN.md';
import ds_cohere from './cohere/DESIGN.md';
import ds_coinbase from './coinbase/DESIGN.md';
import ds_colorful from './colorful/DESIGN.md';
import ds_composio from './composio/DESIGN.md';
import ds_contemporary from './contemporary/DESIGN.md';
import ds_corporate from './corporate/DESIGN.md';
import ds_cosmic from './cosmic/DESIGN.md';
import ds_creative from './creative/DESIGN.md';
import ds_cursor from './cursor/DESIGN.md';
import ds_dashboard from './dashboard/DESIGN.md';
import ds_default from './default/DESIGN.md';
import ds_discord from './discord/DESIGN.md';
import ds_dithered from './dithered/DESIGN.md';
import ds_doodle from './doodle/DESIGN.md';
import ds_dramatic from './dramatic/DESIGN.md';
import ds_duolingo from './duolingo/DESIGN.md';
import ds_editorial from './editorial/DESIGN.md';
import ds_elegant from './elegant/DESIGN.md';
import ds_elevenlabs from './elevenlabs/DESIGN.md';
import ds_energetic from './energetic/DESIGN.md';
import ds_enterprise from './enterprise/DESIGN.md';
import ds_expo from './expo/DESIGN.md';
import ds_expressive from './expressive/DESIGN.md';
import ds_fantasy from './fantasy/DESIGN.md';
import ds_ferrari from './ferrari/DESIGN.md';
import ds_figma from './figma/DESIGN.md';
import ds_flat from './flat/DESIGN.md';
import ds_framer from './framer/DESIGN.md';
import ds_friendly from './friendly/DESIGN.md';
import ds_futuristic from './futuristic/DESIGN.md';
import ds_github from './github/DESIGN.md';
import ds_glassmorphism from './glassmorphism/DESIGN.md';
import ds_gradient from './gradient/DESIGN.md';
import ds_hashicorp from './hashicorp/DESIGN.md';
import ds_hud from './hud/DESIGN.md';
import ds_huggingface from './huggingface/DESIGN.md';
import ds_ibm from './ibm/DESIGN.md';
import ds_intercom from './intercom/DESIGN.md';
import ds_kami from './kami/DESIGN.md';
import ds_kraken from './kraken/DESIGN.md';
import ds_lamborghini from './lamborghini/DESIGN.md';
import ds_levels from './levels/DESIGN.md';
import ds_linear_app from './linear-app/DESIGN.md';
import ds_lingo from './lingo/DESIGN.md';
import ds_loom from './loom/DESIGN.md';
import ds_lovable from './lovable/DESIGN.md';
import ds_luxury from './luxury/DESIGN.md';
import ds_mastercard from './mastercard/DESIGN.md';
import ds_material from './material/DESIGN.md';
import ds_meta from './meta/DESIGN.md';
import ds_minimal from './minimal/DESIGN.md';
import ds_minimax from './minimax/DESIGN.md';
import ds_mintlify from './mintlify/DESIGN.md';
import ds_miro from './miro/DESIGN.md';
import ds_mission_control from './mission-control/DESIGN.md';
import ds_mistral_ai from './mistral-ai/DESIGN.md';
import ds_modern from './modern/DESIGN.md';
import ds_mongodb from './mongodb/DESIGN.md';
import ds_mono from './mono/DESIGN.md';
import ds_neobrutalism from './neobrutalism/DESIGN.md';
import ds_neon from './neon/DESIGN.md';
import ds_neumorphism from './neumorphism/DESIGN.md';
import ds_nike from './nike/DESIGN.md';
import ds_notion from './notion/DESIGN.md';
import ds_nvidia from './nvidia/DESIGN.md';
import ds_ollama from './ollama/DESIGN.md';
import ds_openai from './openai/DESIGN.md';
import ds_opencode_ai from './opencode-ai/DESIGN.md';
import ds_pacman from './pacman/DESIGN.md';
import ds_paper from './paper/DESIGN.md';
import ds_perspective from './perspective/DESIGN.md';
import ds_pinterest from './pinterest/DESIGN.md';
import ds_playstation from './playstation/DESIGN.md';
import ds_posthog from './posthog/DESIGN.md';
import ds_premium from './premium/DESIGN.md';
import ds_professional from './professional/DESIGN.md';
import ds_publication from './publication/DESIGN.md';
import ds_raycast from './raycast/DESIGN.md';
import ds_refined from './refined/DESIGN.md';
import ds_renault from './renault/DESIGN.md';
import ds_replicate from './replicate/DESIGN.md';
import ds_resend from './resend/DESIGN.md';
import ds_retro from './retro/DESIGN.md';
import ds_revolut from './revolut/DESIGN.md';
import ds_runwayml from './runwayml/DESIGN.md';
import ds_sanity from './sanity/DESIGN.md';
import ds_sentry from './sentry/DESIGN.md';
import ds_shadcn from './shadcn/DESIGN.md';
import ds_shopify from './shopify/DESIGN.md';
import ds_simple from './simple/DESIGN.md';
import ds_skeumorphism from './skeumorphism/DESIGN.md';
import ds_slack from './slack/DESIGN.md';
import ds_sleek from './sleek/DESIGN.md';
import ds_spacex from './spacex/DESIGN.md';
import ds_spacious from './spacious/DESIGN.md';
import ds_spotify from './spotify/DESIGN.md';
import ds_starbucks from './starbucks/DESIGN.md';
import ds_storytelling from './storytelling/DESIGN.md';
import ds_stripe from './stripe/DESIGN.md';
import ds_supabase from './supabase/DESIGN.md';
import ds_superhuman from './superhuman/DESIGN.md';
import ds_tesla from './tesla/DESIGN.md';
import ds_tetris from './tetris/DESIGN.md';
import ds_theverge from './theverge/DESIGN.md';
import ds_together_ai from './together-ai/DESIGN.md';
import ds_totality_festival from './totality-festival/DESIGN.md';
import ds_trading_terminal from './trading-terminal/DESIGN.md';
import ds_uber from './uber/DESIGN.md';
import ds_urdu from './urdu/DESIGN.md';
import ds_vercel from './vercel/DESIGN.md';
import ds_vibrant from './vibrant/DESIGN.md';
import ds_vintage from './vintage/DESIGN.md';
import ds_vodafone from './vodafone/DESIGN.md';
import ds_voltagent from './voltagent/DESIGN.md';
import ds_warm_editorial from './warm-editorial/DESIGN.md';
import ds_warp from './warp/DESIGN.md';
import ds_webex from './webex/DESIGN.md';
import ds_webflow from './webflow/DESIGN.md';
import ds_wechat from './wechat/DESIGN.md';
import ds_wired from './wired/DESIGN.md';
import ds_wise from './wise/DESIGN.md';
import ds_x_ai from './x-ai/DESIGN.md';
import ds_xiaohongshu from './xiaohongshu/DESIGN.md';
import ds_zapier from './zapier/DESIGN.md';

export const DESIGN_SYSTEMS: Record<string, any> = {
  'agentic': ds_agentic,
  'airbnb': ds_airbnb,
  'airtable': ds_airtable,
  'ant': ds_ant,
  'apple': ds_apple,
  'application': ds_application,
  'arc': ds_arc,
  'artistic': ds_artistic,
  'atelier-zero': ds_atelier_zero,
  'bento': ds_bento,
  'binance': ds_binance,
  'bmw': ds_bmw,
  'bmw-m': ds_bmw_m,
  'bold': ds_bold,
  'brutalism': ds_brutalism,
  'bugatti': ds_bugatti,
  'cafe': ds_cafe,
  'cal': ds_cal,
  'canva': ds_canva,
  'cisco': ds_cisco,
  'claude': ds_claude,
  'clay': ds_clay,
  'claymorphism': ds_claymorphism,
  'clean': ds_clean,
  'clickhouse': ds_clickhouse,
  'cohere': ds_cohere,
  'coinbase': ds_coinbase,
  'colorful': ds_colorful,
  'composio': ds_composio,
  'contemporary': ds_contemporary,
  'corporate': ds_corporate,
  'cosmic': ds_cosmic,
  'creative': ds_creative,
  'cursor': ds_cursor,
  'dashboard': ds_dashboard,
  'default': ds_default,
  'discord': ds_discord,
  'dithered': ds_dithered,
  'doodle': ds_doodle,
  'dramatic': ds_dramatic,
  'duolingo': ds_duolingo,
  'editorial': ds_editorial,
  'elegant': ds_elegant,
  'elevenlabs': ds_elevenlabs,
  'energetic': ds_energetic,
  'enterprise': ds_enterprise,
  'expo': ds_expo,
  'expressive': ds_expressive,
  'fantasy': ds_fantasy,
  'ferrari': ds_ferrari,
  'figma': ds_figma,
  'flat': ds_flat,
  'framer': ds_framer,
  'friendly': ds_friendly,
  'futuristic': ds_futuristic,
  'github': ds_github,
  'glassmorphism': ds_glassmorphism,
  'gradient': ds_gradient,
  'hashicorp': ds_hashicorp,
  'hud': ds_hud,
  'huggingface': ds_huggingface,
  'ibm': ds_ibm,
  'intercom': ds_intercom,
  'kami': ds_kami,
  'kraken': ds_kraken,
  'lamborghini': ds_lamborghini,
  'levels': ds_levels,
  'linear-app': ds_linear_app,
  'lingo': ds_lingo,
  'loom': ds_loom,
  'lovable': ds_lovable,
  'luxury': ds_luxury,
  'mastercard': ds_mastercard,
  'material': ds_material,
  'meta': ds_meta,
  'minimal': ds_minimal,
  'minimax': ds_minimax,
  'mintlify': ds_mintlify,
  'miro': ds_miro,
  'mission-control': ds_mission_control,
  'mistral-ai': ds_mistral_ai,
  'modern': ds_modern,
  'mongodb': ds_mongodb,
  'mono': ds_mono,
  'neobrutalism': ds_neobrutalism,
  'neon': ds_neon,
  'neumorphism': ds_neumorphism,
  'nike': ds_nike,
  'notion': ds_notion,
  'nvidia': ds_nvidia,
  'ollama': ds_ollama,
  'openai': ds_openai,
  'opencode-ai': ds_opencode_ai,
  'pacman': ds_pacman,
  'paper': ds_paper,
  'perspective': ds_perspective,
  'pinterest': ds_pinterest,
  'playstation': ds_playstation,
  'posthog': ds_posthog,
  'premium': ds_premium,
  'professional': ds_professional,
  'publication': ds_publication,
  'raycast': ds_raycast,
  'refined': ds_refined,
  'renault': ds_renault,
  'replicate': ds_replicate,
  'resend': ds_resend,
  'retro': ds_retro,
  'revolut': ds_revolut,
  'runwayml': ds_runwayml,
  'sanity': ds_sanity,
  'sentry': ds_sentry,
  'shadcn': ds_shadcn,
  'shopify': ds_shopify,
  'simple': ds_simple,
  'skeumorphism': ds_skeumorphism,
  'slack': ds_slack,
  'sleek': ds_sleek,
  'spacex': ds_spacex,
  'spacious': ds_spacious,
  'spotify': ds_spotify,
  'starbucks': ds_starbucks,
  'storytelling': ds_storytelling,
  'stripe': ds_stripe,
  'supabase': ds_supabase,
  'superhuman': ds_superhuman,
  'tesla': ds_tesla,
  'tetris': ds_tetris,
  'theverge': ds_theverge,
  'together-ai': ds_together_ai,
  'totality-festival': ds_totality_festival,
  'trading-terminal': ds_trading_terminal,
  'uber': ds_uber,
  'urdu': ds_urdu,
  'vercel': ds_vercel,
  'vibrant': ds_vibrant,
  'vintage': ds_vintage,
  'vodafone': ds_vodafone,
  'voltagent': ds_voltagent,
  'warm-editorial': ds_warm_editorial,
  'warp': ds_warp,
  'webex': ds_webex,
  'webflow': ds_webflow,
  'wechat': ds_wechat,
  'wired': ds_wired,
  'wise': ds_wise,
  'x-ai': ds_x_ai,
  'xiaohongshu': ds_xiaohongshu,
  'zapier': ds_zapier
};

export type DesignSystemName = keyof typeof DESIGN_SYSTEMS;

export * from './parser';
