/**
 * AUTO-GENERATED DESIGN SYSTEM INDEX
 * A compact summary for the CEO agent to pick the right design system.
 */

export const DESIGN_SYSTEM_INDEX = `
DESIGN SYSTEM INDEX (pick the best match for the task):
- agentic: > Category: Themed & Unique > Conversational AI-first interface with minimal controls, clear outc...
- airbnb: > Category: E-Commerce & Retail > Travel marketplace. Warm coral accent, photography-driven, roun...
- airtable: > Category: Design & Creative > Spreadsheet-database hybrid. Colorful, friendly, structured data ...
- ant: > Category: Professional & Corporate > Structured, enterprise-focused design system emphasizing c...
- apple: > Category: Media & Consumer > Consumer electronics. Premium white space, SF Pro, cinematic imagery.
- application: > Category: Professional & Corporate > App dashboard with purple-themed aesthetic, top-bar naviga...
- arc: > Category: Productivity & SaaS > "The browser that browses for you." Translucent surfaces, gradi...
- artistic: > Category: Creative & Artistic > High-contrast, expressive style with creative typography and bo...
- atelier-zero: > Category: Editorial · Studio > A magazine-grade, collage-driven visual system: warm paper canva...
- bento: > Category: Layout & Structure > Modular grid layout with card-like blocks, clear hierarchy, soft...
- binance: > Category: Fintech & Crypto > Crypto exchange. Bold yellow accent on monochrome, trading-floor u...
- bmw: > Category: Automotive > Luxury automotive. Dark premium surfaces, precise German engineering aes...
- bmw-m: > Category: Automotive > Motorsport performance sub-brand. Near-black cockpit surfaces, BMW M tri...
- bold: > Category: Bold & Expressive > Strong visual presence with heavyweight typography, high-contrast...
- brutalism: > Category: Bold & Expressive > Raw, anti-design aesthetic inspired by concrete architecture with...
- bugatti: > Category: Automotive > Hypercar brand. Cinema-black canvas, monochrome austerity, monumental di...
- cafe: > Category: Creative & Artistic > Cozy cafe-inspired interface with warm tones, soft typography, ...
- cal: > Category: Productivity & SaaS > Open-source scheduling. Clean neutral UI, developer-oriented si...
- canva: > Category: Design & Creative > Visual creation platform. Vivid purple-blue gradient, generous sp...
- cisco: > Category: Backend & Data > Enterprise infrastructure brand. Dark trust surfaces, Cisco Blue sig...
- claude: > Category: AI & LLM > Anthropic's AI assistant. Warm terracotta accent, clean editorial layout.
- clay: > Category: Design & Creative > Creative agency. Organic shapes, soft gradients, art-directed lay...
- claymorphism: > Category: Morphism & Effects > Soft, rounded 3D-like shapes mimicking malleable clay with playf...
- clean: > Category: Modern & Minimal > Simplicity-focused design with ample whitespace, legible typograph...
- clickhouse: > Category: Backend & Data > Fast analytics database. Yellow-accented, technical documentation st...
- cohere: > Category: AI & LLM > Enterprise AI platform. Vibrant gradients, data-rich dashboard aesthetic.
- coinbase: > Category: Fintech & Crypto > Crypto exchange. Clean blue identity, trust-focused, institutional...
- colorful: > Category: Bold & Expressive > Vibrant, high-contrast palettes and gradients for engaging, memor...
- composio: > Category: Backend & Data > Tool integration platform. Modern dark with colorful integration icons.
- contemporary: > Category: Modern & Minimal > Current-era minimalist design with bento grids, dark mode support,...
- corporate: > Category: Professional & Corporate > Professional, brand-aligned design with structured grids, ...
- cosmic: > Category: Creative & Artistic > Futuristic sci-fi aesthetic with dark themes, vibrant neon acce...
- creative: > Category: Creative & Artistic > Playful, character-driven design with expressive typography and...
- cursor: > Category: Developer Tools > AI-first code editor. Sleek dark interface, gradient accents.
- dashboard: > Category: Professional & Corporate > Dark-themed cloud-platform aesthetic with modular grids, g...
- default: > Category: Starter > A clean, product-oriented default. Use when the brief doesn't call for a > ...
- discord: > Category: Productivity & SaaS > Voice / chat platform. Deep blurple, dark-first surfaces, playf...
- dithered: > Category: Retro & Nostalgic > Dot-pattern rendering technique that simulates shades with a limi...
- doodle: > Category: Creative & Artistic > Hand-drawn, sketch-like style with doodles, handwritten fonts, ...
- dramatic: > Category: Bold & Expressive > High-contrast, theatrical design with bold layouts, immersive vis...
- duolingo: > Category: Productivity & SaaS > Language-learning platform. Bright owl green, chunky shadows, g...
- editorial: > Category: Creative & Artistic > Magazine-inspired editorial layout with refined serif typograph...
- elegant: > Category: Professional & Corporate > Graceful, refined aesthetic with delicate typography, mini...
- elevenlabs: > Category: AI & LLM > AI voice platform. Dark cinematic UI, audio-waveform aesthetics.
- energetic: > Category: Bold & Expressive > Dynamic, vibrant style with thick borders, geometric shapes, high...
- enterprise: > Category: Professional & Corporate > Clean, high-contrast enterprise design for data-driven wor...
- expo: > Category: Developer Tools > React Native platform. Dark theme, tight letter-spacing, code-centric.
- expressive: > Category: Bold & Expressive > Vibrant, personality-driven design with bold colors, playful grap...
- fantasy: > Category: Creative & Artistic > Game-inspired fantasy aesthetic with bold, premium visuals, ric...
- ferrari: > Category: Automotive > Luxury automotive. Chiaroscuro editorial, Ferrari Red accents, cinematic...
- figma: > Category: Design & Creative > Collaborative design tool. Vibrant multi-color, playful yet profe...
- flat: > Category: Modern & Minimal > Two-dimensional minimalist style with vibrant colors, clean typogr...
- framer: > Category: Design & Creative > Website builder. Bold black and blue, motion-first, design-forward.
- friendly: > Category: Creative & Artistic > Approachable, intuitive design with rounded elements, ample whi...
- futuristic: > Category: Themed & Unique > Forward-looking design with tech-inspired typography, modern layout...
- github: > Category: Developer Tools > Code-forward platform. Functional density, blue-on-white precision,...
- glassmorphism: > Category: Morphism & Effects > Frosted glass effect with translucent layers, subtle blur, and l...
- gradient: > Category: Morphism & Effects > Smooth color transitions and gradient-rich surfaces for modern, ...
- hashicorp: > Category: Backend & Data > Infrastructure automation. Enterprise-clean, black and white.
- hud: > Category: Themed & Unique > Fighter jet / helicopter head-up display. Phosphor green on near-bl...
- huggingface: > Category: AI & LLM > ML community hub. Sunny yellow accent, monospace identity, cheerful and de...
- ibm: > Category: Media & Consumer > Enterprise technology. Carbon design system, structured blue palette.
- intercom: > Category: Productivity & SaaS > Customer messaging. Friendly blue palette, conversational UI pa...
- kami: > Category: Editorial & Print > Editorial paper system: warm parchment canvas, ink-blue accent, s...
- kraken: > Category: Fintech & Crypto > Crypto trading. Purple-accented dark UI, data-dense dashboards.
- lamborghini: > Category: Automotive > Supercar brand. True black surfaces, gold accents, dramatic uppercase ty...
- levels: > Category: Layout & Structure > Conversion-focused design that removes friction and guides users...
- linear-app: > Category: Productivity & SaaS > Project management. Ultra-minimal, precise, purple accent.
- lingo: > Category: Creative & Artistic > Playful, minimal design with bright colors, rounded shapes, tac...
- loom: > Category: Themed & Unique > Loom async video. Purple primary, friendly surfaces, video-first la...
- lovable: > Category: Developer Tools > AI full-stack builder. Playful gradients, friendly dev aesthetic.
- luxury: > Category: Professional & Corporate > High-end dark aesthetic with bold headings, monochromatic ...
- mastercard: > Category: Fintech & Crypto > Global payments network. Warm cream canvas, orbital pill shapes, e...
- material: > Category: Professional & Corporate > Google's Material Design with layered surfaces, dynamic th...
- meta: > Category: E-Commerce & Retail > Tech retail store. Photography-first, binary light/dark surface...
- minimal: > Category: Modern & Minimal > Stripped-back design emphasizing whitespace, clean typography, and...
- minimax: > Category: AI & LLM > AI model provider. Bold dark interface with neon accents.
- mintlify: > Category: Productivity & SaaS > Documentation platform. Clean, green-accented, reading-optimized.
- miro: > Category: Design & Creative > Visual collaboration. Bright yellow accent, infinite canvas aesth...
- mission-control: > Category: Developer Tools > Space/aerospace mission monitoring. Dark command center, amber tele...
- mistral-ai: > Category: AI & LLM > Open-weight LLM provider. French-engineered minimalism, purple-toned.
- modern: > Category: Modern & Minimal > Contemporary editorial style with serif typography, minimal palett...
- mongodb: > Category: Backend & Data > Document database. Green leaf branding, developer documentation focus.
- mono: > Category: Modern & Minimal > Monospace-driven, matrix-inspired design with high-contrast elemen...
- neobrutalism: > Category: Bold & Expressive > Modern take on brutalism with bold borders, vivid accent colors, ...
- neon: > Category: Morphism & Effects > Electric neon glow effects with high-contrast color pairings for...
- neumorphism: > Category: Morphism & Effects > Soft, extruded UI elements with inner and outer shadows on monoc...
- nike: > Category: E-Commerce & Retail > Athletic retail. Monochrome UI, massive uppercase type, full-bl...
- notion: > Category: Productivity & SaaS > All-in-one workspace. Warm minimalism, serif headings, soft sur...
- nvidia: > Category: Media & Consumer > GPU computing. Green-black energy, technical power aesthetic.
- ollama: > Category: AI & LLM > Run LLMs locally. Terminal-first, monochrome simplicity.
- openai: > Category: AI & LLM > Calm, near-monochrome system anchored in deep teal-black with generous whi...
- opencode-ai: > Category: AI & LLM > AI coding platform. Developer-centric dark theme.
- pacman: > Category: Themed & Unique > Retro arcade-inspired design with pixel fonts, dotted borders, play...
- paper: > Category: Retro & Nostalgic > Paper-textured, print-inspired design with minimal colors, clean ...
- perspective: > Category: Layout & Structure > Spatial depth design with isometric views, vanishing points, and...
- pinterest: > Category: Media & Consumer > Visual discovery. Red accent, masonry grid, image-first.
- playstation: > Category: Media & Consumer > Gaming console retail. Three-surface channel layout, quiet-authori...
- posthog: > Category: Backend & Data > Product analytics. Playful hedgehog branding, developer-friendly dar...
- premium: > Category: Professional & Corporate > Apple-inspired premium aesthetic with precise spacing, mod...
- professional: > Category: Professional & Corporate > Polished, business-ready design with modern typography, st...
- publication: > Category: Creative & Artistic > Print-inspired visual language for books, magazines, and report...
- raycast: > Category: Developer Tools > Productivity launcher. Sleek dark chrome, vibrant gradient accents.
- refined: > Category: Modern & Minimal > Carefully curated, modern minimal style with elegant serif typogra...
- renault: > Category: Automotive > French automotive. Vibrant aurora gradients, NouvelR typography, bold en...
- replicate: > Category: AI & LLM > Run ML models via API. Clean white canvas, code-forward.
- resend: > Category: Productivity & SaaS > Email API. Minimal dark theme, monospace accents.
- retro: > Category: Retro & Nostalgic > Throwback design with vintage-inspired typography, high-contrast ...
- revolut: > Category: Fintech & Crypto > Digital banking. Sleek dark interface, gradient cards, fintech pre...
- runwayml: > Category: AI & LLM > AI video generation. Cinematic dark UI, media-rich layout.
- sanity: > Category: Backend & Data > Headless CMS. Red accent, content-first editorial layout.
- sentry: > Category: Backend & Data > Error monitoring. Dark dashboard, data-dense, pink-purple accent.
- shadcn: > Category: Modern & Minimal > Shadcn/ui-inspired design with minimal, clean components, monochro...
- shopify: > Category: E-Commerce & Retail > E-commerce platform. Dark-first cinematic, neon green accent, u...
- simple: > Category: Modern & Minimal > Straightforward, no-frills design with clean typography, neutral c...
- skeumorphism: > Category: Morphism & Effects > Real-world mimicry with textured surfaces, 3D effects, and famil...
- slack: > Category: Productivity & SaaS > Workplace communication platform. Aubergine-primary, multi-acce...
- sleek: > Category: Modern & Minimal > Modern minimalist aesthetic with clean lines, intentional color pa...
- spacex: > Category: Media & Consumer > Space technology. Stark black and white, full-bleed imagery, futur...
- spacious: > Category: Layout & Structure > Generous whitespace, consistent padding, and grid-based layouts ...
- spotify: > Category: Media & Consumer > Music streaming. Vibrant green on dark, bold type, album-art-driven.
- starbucks: > Category: E-Commerce & Retail > Global coffee retail brand. Four-tier green system, warm cream ...
- storytelling: > Category: Creative & Artistic > Narrative-driven design using visuals, copy, and interaction to...
- stripe: > Category: Fintech & Crypto > Payment infrastructure. Signature purple gradients, weight-300 ele...
- supabase: > Category: Backend & Data > Open-source Firebase alternative. Dark emerald theme, code-first.
- superhuman: > Category: Developer Tools > Fast email client. Premium dark UI, keyboard-first, purple glow.
- tesla: > Category: Automotive > Electric automotive. Radical subtraction, full-viewport photography, nea...
- tetris: > Category: Themed & Unique > Classic block-game inspired design with playful colors, bold displa...
- theverge: > Category: Media & Consumer > Tech editorial media. Acid-mint and ultraviolet accents, Manuka di...
- together-ai: > Category: AI & LLM > Open-source AI infrastructure. Technical, blueprint-style design.
- totality-festival: > Category: Themed & Unique > Surface: web > A cosmic-premium, glassmorphic dark system that capt...
- trading-terminal: > Category: Themed & Unique > Bloomberg-style financial trading terminal. Dark-only, data-dense, ...
- uber: > Category: Media & Consumer > Mobility platform. Bold black and white, tight type, urban energy.
- urdu: > Category: Editorial / Personal / Publication Urdu-first digital experiences with native RTL sup...
- vercel: > Category: Developer Tools > Frontend deployment. Black and white precision, Geist font.
- vibrant: > Category: Bold & Expressive > Lively, colorful design with bold playful typography, warm accent...
- vintage: > Category: Retro & Nostalgic > 1950s-1990s nostalgia with skeuomorphic touches, grainy textures,...
- vodafone: > Category: Media & Consumer > Global telecom brand. Monumental uppercase display, Vodafone Red c...
- voltagent: > Category: AI & LLM > AI agent framework. Void-black canvas, emerald accent, terminal-native.
- warm-editorial: > Category: Starter > A serif-led magazine aesthetic. Terracotta accent on warm off-white paper —...
- warp: > Category: Developer Tools > Modern terminal. Dark IDE-like interface, block-based command UI.
- webex: > Category: Productivity & SaaS > Collaboration platform. Momentum typography, blue action system...
- webflow: > Category: Design & Creative > Visual web builder. Blue-accented, polished marketing site aesthe...
- wechat: > Category: Social & Messaging > Brand visual language for WeChat Mini Programs, official account...
- wired: > Category: Media & Consumer > Tech magazine. Paper-white broadsheet density, custom serif displa...
- wise: > Category: Fintech & Crypto > Money transfer. Bright green accent, friendly and clear.
- x-ai: > Category: AI & LLM > Elon Musk's AI lab. Stark monochrome, futuristic minimalism.
- xiaohongshu: > Category: Media & Consumer > Lifestyle UGC social platform. Singular brand red, generous radius...
- zapier: > Category: Productivity & SaaS > Automation platform. Warm orange, friendly illustration-driven.
`.trim();

export function getDesignSystemIndex(): string {
  return DESIGN_SYSTEM_INDEX;
}
