// Auto-generated by scripts/gen_registry.js
import skill_8_bit_orbit_video_template from './8-bit-orbit-video-template/SKILL.md?raw';
import skill_ad_creative from './ad-creative/SKILL.md?raw';
import skill_after_hours_editorial_template from './after-hours-editorial-template/SKILL.md?raw';
import skill_agent_browser from './agent-browser/SKILL.md?raw';
import skill_ai_music_album from './ai-music-album/SKILL.md?raw';
import skill_algorithmic_art from './algorithmic-art/SKILL.md?raw';
import skill_apple_hig from './apple-hig/SKILL.md?raw';
import skill_artifacts_builder from './artifacts-builder/SKILL.md?raw';
import skill_brainstorming from './brainstorming/SKILL.md?raw';
import skill_brand_guidelines from './brand-guidelines/SKILL.md?raw';
import skill_canvas_design from './canvas-design/SKILL.md?raw';
import skill_color_expert from './color-expert/SKILL.md?raw';
import skill_competitive_ads_extractor from './competitive-ads-extractor/SKILL.md?raw';
import skill_copywriting from './copywriting/SKILL.md?raw';
import skill_creative_director from './creative-director/SKILL.md?raw';
import skill_d3_visualization from './d3-visualization/SKILL.md?raw';
import skill_design_brief from './design-brief/SKILL.md?raw';
import skill_design_consultation from './design-consultation/SKILL.md?raw';
import skill_design_md from './design-md/SKILL.md?raw';
import skill_design_review from './design-review/SKILL.md?raw';
import skill_digits_fintech_swiss_template from './digits-fintech-swiss-template/SKILL.md?raw';
import skill_doc from './doc/SKILL.md?raw';
import skill_docx from './docx/SKILL.md?raw';
import skill_domain_name_brainstormer from './domain-name-brainstormer/SKILL.md?raw';
import skill_editorial_burgundy_principles_template from './editorial-burgundy-principles-template/SKILL.md?raw';
import skill_enhance_prompt from './enhance-prompt/SKILL.md?raw';
import skill_fal_3d from './fal-3d/SKILL.md?raw';
import skill_fal_generate from './fal-generate/SKILL.md?raw';
import skill_fal_image_edit from './fal-image-edit/SKILL.md?raw';
import skill_fal_kling_o3 from './fal-kling-o3/SKILL.md?raw';
import skill_fal_lip_sync from './fal-lip-sync/SKILL.md?raw';
import skill_fal_realtime from './fal-realtime/SKILL.md?raw';
import skill_fal_restore from './fal-restore/SKILL.md?raw';
import skill_fal_train from './fal-train/SKILL.md?raw';
import skill_fal_tryon from './fal-tryon/SKILL.md?raw';
import skill_fal_upscale from './fal-upscale/SKILL.md?raw';
import skill_fal_video_edit from './fal-video-edit/SKILL.md?raw';
import skill_fal_vision from './fal-vision/SKILL.md?raw';
import skill_faq_page from './faq-page/SKILL.md?raw';
import skill_field_notes_editorial_template from './field-notes-editorial-template/SKILL.md?raw';
import skill_figma_code_connect_components from './figma-code-connect-components/SKILL.md?raw';
import skill_figma_create_design_system_rules from './figma-create-design-system-rules/SKILL.md?raw';
import skill_figma_create_new_file from './figma-create-new-file/SKILL.md?raw';
import skill_figma_generate_design from './figma-generate-design/SKILL.md?raw';
import skill_figma_generate_library from './figma-generate-library/SKILL.md?raw';
import skill_figma_implement_design from './figma-implement-design/SKILL.md?raw';
import skill_figma_use from './figma-use/SKILL.md?raw';
import skill_flutter_animating_apps from './flutter-animating-apps/SKILL.md?raw';
import skill_frontend_design from './frontend-design/SKILL.md?raw';
import skill_frontend_dev from './frontend-dev/SKILL.md?raw';
import skill_frontend_skill from './frontend-skill/SKILL.md?raw';
import skill_frontend_slides from './frontend-slides/SKILL.md?raw';
import skill_full_page_screenshot from './full-page-screenshot/SKILL.md?raw';
import skill_gif_sticker_maker from './gif-sticker-maker/SKILL.md?raw';
import skill_gsap_core from './gsap-core/SKILL.md?raw';
import skill_gsap_react from './gsap-react/SKILL.md?raw';
import skill_gsap_scrolltrigger from './gsap-scrolltrigger/SKILL.md?raw';
import skill_gsap_timeline from './gsap-timeline/SKILL.md?raw';
import skill_hand_drawn_diagrams from './hand-drawn-diagrams/SKILL.md?raw';
import skill_hatch_pet from './hatch-pet/SKILL.md?raw';
import skill_html_ppt_retro_quarterly_review from './html-ppt-retro-quarterly-review/SKILL.md?raw';
import skill_image_enhancer from './image-enhancer/SKILL.md?raw';
import skill_imagegen from './imagegen/SKILL.md?raw';
import skill_imagen from './imagen/SKILL.md?raw';
import skill_login_flow from './login-flow/SKILL.md?raw';
import skill_marketing_psychology from './marketing-psychology/SKILL.md?raw';
import skill_minimax_docx from './minimax-docx/SKILL.md?raw';
import skill_minimax_pdf from './minimax-pdf/SKILL.md?raw';
import skill_nanobanana_ppt from './nanobanana-ppt/SKILL.md?raw';
import skill_paywall_upgrade_cro from './paywall-upgrade-cro/SKILL.md?raw';
import skill_pdf from './pdf/SKILL.md?raw';
import skill_pixelbin_media from './pixelbin-media/SKILL.md?raw';
import skill_plan_design_review from './plan-design-review/SKILL.md?raw';
import skill_platform_design from './platform-design/SKILL.md?raw';
import skill_pptx from './pptx/SKILL.md?raw';
import skill_pptx_generator from './pptx-generator/SKILL.md?raw';
import skill_pptx_html_fidelity_audit from './pptx-html-fidelity-audit/SKILL.md?raw';
import skill_release_notes_one_pager from './release-notes-one-pager/SKILL.md?raw';
import skill_remotion from './remotion/SKILL.md?raw';
import skill_replicate from './replicate/SKILL.md?raw';
import skill_screenshot from './screenshot/SKILL.md?raw';
import skill_screenshots_marketing from './screenshots-marketing/SKILL.md?raw';
import skill_shadcn_ui from './shadcn-ui/SKILL.md?raw';
import skill_shader_dev from './shader-dev/SKILL.md?raw';
import skill_slack_gif_creator from './slack-gif-creator/SKILL.md?raw';
import skill_slides from './slides/SKILL.md?raw';
import skill_sora from './sora/SKILL.md?raw';
import skill_speech from './speech/SKILL.md?raw';
import skill_stitch_loop from './stitch-loop/SKILL.md?raw';
import skill_swiftui_design from './swiftui-design/SKILL.md?raw';
import skill_swiss_creative_mode_template from './swiss-creative-mode-template/SKILL.md?raw';
import skill_swiss_user_research_video_template from './swiss-user-research-video-template/SKILL.md?raw';
import skill_taste_skill from './taste-skill/SKILL.md?raw';
import skill_theme_factory from './theme-factory/SKILL.md?raw';
import skill_threejs from './threejs/SKILL.md?raw';
import skill_ui_skills from './ui-skills/SKILL.md?raw';
import skill_ui_ux_pro_max from './ui-ux-pro-max/SKILL.md?raw';
import skill_venice_audio_music from './venice-audio-music/SKILL.md?raw';
import skill_venice_audio_speech from './venice-audio-speech/SKILL.md?raw';
import skill_venice_image_edit from './venice-image-edit/SKILL.md?raw';
import skill_venice_image_generate from './venice-image-generate/SKILL.md?raw';
import skill_venice_video from './venice-video/SKILL.md?raw';
import skill_video_downloader from './video-downloader/SKILL.md?raw';
import skill_web_artifacts_builder from './web-artifacts-builder/SKILL.md?raw';
import skill_web_design_guidelines from './web-design-guidelines/SKILL.md?raw';
import skill_wpds from './wpds/SKILL.md?raw';
import skill_youtube_clipper from './youtube-clipper/SKILL.md?raw';

export const SKILL_REGISTRY: Record<string, any> = {
  '8-bit-orbit-video-template': skill_8_bit_orbit_video_template,
  'ad-creative': skill_ad_creative,
  'after-hours-editorial-template': skill_after_hours_editorial_template,
  'agent-browser': skill_agent_browser,
  'ai-music-album': skill_ai_music_album,
  'algorithmic-art': skill_algorithmic_art,
  'apple-hig': skill_apple_hig,
  'artifacts-builder': skill_artifacts_builder,
  'brainstorming': skill_brainstorming,
  'brand-guidelines': skill_brand_guidelines,
  'canvas-design': skill_canvas_design,
  'color-expert': skill_color_expert,
  'competitive-ads-extractor': skill_competitive_ads_extractor,
  'copywriting': skill_copywriting,
  'creative-director': skill_creative_director,
  'd3-visualization': skill_d3_visualization,
  'design-brief': skill_design_brief,
  'design-consultation': skill_design_consultation,
  'design-md': skill_design_md,
  'design-review': skill_design_review,
  'digits-fintech-swiss-template': skill_digits_fintech_swiss_template,
  'doc': skill_doc,
  'docx': skill_docx,
  'domain-name-brainstormer': skill_domain_name_brainstormer,
  'editorial-burgundy-principles-template': skill_editorial_burgundy_principles_template,
  'enhance-prompt': skill_enhance_prompt,
  'fal-3d': skill_fal_3d,
  'fal-generate': skill_fal_generate,
  'fal-image-edit': skill_fal_image_edit,
  'fal-kling-o3': skill_fal_kling_o3,
  'fal-lip-sync': skill_fal_lip_sync,
  'fal-realtime': skill_fal_realtime,
  'fal-restore': skill_fal_restore,
  'fal-train': skill_fal_train,
  'fal-tryon': skill_fal_tryon,
  'fal-upscale': skill_fal_upscale,
  'fal-video-edit': skill_fal_video_edit,
  'fal-vision': skill_fal_vision,
  'faq-page': skill_faq_page,
  'field-notes-editorial-template': skill_field_notes_editorial_template,
  'figma-code-connect-components': skill_figma_code_connect_components,
  'figma-create-design-system-rules': skill_figma_create_design_system_rules,
  'figma-create-new-file': skill_figma_create_new_file,
  'figma-generate-design': skill_figma_generate_design,
  'figma-generate-library': skill_figma_generate_library,
  'figma-implement-design': skill_figma_implement_design,
  'figma-use': skill_figma_use,
  'flutter-animating-apps': skill_flutter_animating_apps,
  'frontend-design': skill_frontend_design,
  'frontend-dev': skill_frontend_dev,
  'frontend-skill': skill_frontend_skill,
  'frontend-slides': skill_frontend_slides,
  'full-page-screenshot': skill_full_page_screenshot,
  'gif-sticker-maker': skill_gif_sticker_maker,
  'gsap-core': skill_gsap_core,
  'gsap-react': skill_gsap_react,
  'gsap-scrolltrigger': skill_gsap_scrolltrigger,
  'gsap-timeline': skill_gsap_timeline,
  'hand-drawn-diagrams': skill_hand_drawn_diagrams,
  'hatch-pet': skill_hatch_pet,
  'html-ppt-retro-quarterly-review': skill_html_ppt_retro_quarterly_review,
  'image-enhancer': skill_image_enhancer,
  'imagegen': skill_imagegen,
  'imagen': skill_imagen,
  'login-flow': skill_login_flow,
  'marketing-psychology': skill_marketing_psychology,
  'minimax-docx': skill_minimax_docx,
  'minimax-pdf': skill_minimax_pdf,
  'nanobanana-ppt': skill_nanobanana_ppt,
  'paywall-upgrade-cro': skill_paywall_upgrade_cro,
  'pdf': skill_pdf,
  'pixelbin-media': skill_pixelbin_media,
  'plan-design-review': skill_plan_design_review,
  'platform-design': skill_platform_design,
  'pptx': skill_pptx,
  'pptx-generator': skill_pptx_generator,
  'pptx-html-fidelity-audit': skill_pptx_html_fidelity_audit,
  'release-notes-one-pager': skill_release_notes_one_pager,
  'remotion': skill_remotion,
  'replicate': skill_replicate,
  'screenshot': skill_screenshot,
  'screenshots-marketing': skill_screenshots_marketing,
  'shadcn-ui': skill_shadcn_ui,
  'shader-dev': skill_shader_dev,
  'slack-gif-creator': skill_slack_gif_creator,
  'slides': skill_slides,
  'sora': skill_sora,
  'speech': skill_speech,
  'stitch-loop': skill_stitch_loop,
  'swiftui-design': skill_swiftui_design,
  'swiss-creative-mode-template': skill_swiss_creative_mode_template,
  'swiss-user-research-video-template': skill_swiss_user_research_video_template,
  'taste-skill': skill_taste_skill,
  'theme-factory': skill_theme_factory,
  'threejs': skill_threejs,
  'ui-skills': skill_ui_skills,
  'ui-ux-pro-max': skill_ui_ux_pro_max,
  'venice-audio-music': skill_venice_audio_music,
  'venice-audio-speech': skill_venice_audio_speech,
  'venice-image-edit': skill_venice_image_edit,
  'venice-image-generate': skill_venice_image_generate,
  'venice-video': skill_venice_video,
  'video-downloader': skill_video_downloader,
  'web-artifacts-builder': skill_web_artifacts_builder,
  'web-design-guidelines': skill_web_design_guidelines,
  'wpds': skill_wpds,
  'youtube-clipper': skill_youtube_clipper
};

export type SkillName = keyof typeof SKILL_REGISTRY;

export * from './loader';
