const fs = require('fs');
const path = require('path');

const skillsDir = path.join(__dirname, '../src/lib/skills');
const outputFile = path.join(skillsDir, 'index.ts');

function generateRegistry() {
  const folders = fs.readdirSync(skillsDir).filter(f => {
    const fullPath = path.join(skillsDir, f);
    const hasSkill = fs.existsSync(path.join(fullPath, 'SKILL.md'));
    return fs.statSync(fullPath).isDirectory() && !f.startsWith('_') && hasSkill;
  });

  const imports = folders.map(f => `import skill_${f.replace(/[^a-zA-Z0-9]/g, '_')} from './${f}/SKILL.md?raw';`).join('\n');
  const exportList = folders.map(f => `  '${f}': skill_${f.replace(/[^a-zA-Z0-9]/g, '_')}`).join(',\n');

  const content = `// Auto-generated by scripts/gen_registry.js
${imports}

export const SKILL_REGISTRY: Record<string, any> = {
${exportList}
};

export type SkillName = keyof typeof SKILL_REGISTRY;
`;

  fs.writeFileSync(outputFile, content);
  console.log(`Generated ${outputFile}`);
}

generateRegistry();
