const fs = require('fs');
const path = require('path');

const dsDir = path.join(__dirname, '../src/lib/design-systems');
const outputFile = path.join(dsDir, 'index.ts');

function generateIndex() {
  const folders = fs.readdirSync(dsDir).filter(f => {
    const fullPath = path.join(dsDir, f);
    const hasDesign = fs.existsSync(path.join(fullPath, 'DESIGN.md'));
    return fs.statSync(fullPath).isDirectory() && !f.startsWith('_') && hasDesign;
  });

  const imports = folders.map(f => `import ds_${f.replace(/[^a-zA-Z0-9]/g, '_')} from './${f}/DESIGN.md';`).join('\n');
  const exportList = folders.map(f => `  '${f}': ds_${f.replace(/[^a-zA-Z0-9]/g, '_')}`).join(',\n');

  const content = `// Auto-generated by scripts/gen_ds_index.js
${imports}

export const DESIGN_SYSTEMS: Record<string, any> = {
${exportList}
};

export type DesignSystemName = keyof typeof DESIGN_SYSTEMS;
`;

  fs.writeFileSync(outputFile, content);
  console.log(`Generated ${outputFile}`);
}

generateIndex();
